"""Obsidian Knowledge Vault Markdown Formatter.

Conforms to Protocol #10 (Agent-First Obsidian Integration & Wikilinks).
"""

from __future__ import annotations

from pathlib import Path
from typing import List

from rag_sync.models import CodeChunk, SyncResult


def format_obsidian_codebase_note(
    repo_name: str,
    sync_result: SyncResult,
    chunks: List[CodeChunk],
) -> str:
    """Generate an atomic Zettel / MOC note for the synced repository in Obsidian."""
    date_str = sync_result.timestamp[:10]

    md = f"""---
title: "Codebase Index: {repo_name}"
tags:
  - codebase
  - rag-index
  - semantic-search
  - automated-sync
date: {date_str}
updated_at: {sync_result.timestamp}
---

# Codebase Knowledge: {repo_name}

> Automated AST semantic index generated by `n8n-rag-knowledge-sync-hub`.

## 📊 Synchronization Metrics

| Metric | Value |
|---|---|
| **Files Scanned** | `{sync_result.total_files_scanned}` |
| **Total Chunks Extracted** | `{sync_result.chunks_extracted}` |
| **New Chunks Indexed** | `{sync_result.new_chunks_indexed}` |
| **Skipped Duplicates** | `{sync_result.skipped_duplicates}` |
| **Sync Latency** | `{sync_result.execution_time_ms:.2f} ms` |

---

## 🧩 Extracted Semantic Entities

| Entity Name | Kind | File Path | Lines | Hash |
|---|---|---|:---:|:---:|
"""

    for c in chunks[:50]:  # Cap to top 50 in MOC note
        md += f"| `{c.name}` | `{c.chunk_type}` | `{c.file_path}` | `{c.line_start}-{c.line_end}` | `{c.content_hash[:8]}` |\n"

    md += f"""
---

## 🔗 Related Knowledge
- [[00_Atlas/Home|Home Atlas]]
- [[00_Atlas/MOCs/MOC - Portfolio de Ingenieria|Portfolio de Ingeniería]]
"""
    return md
